name: Request a bug
description: 'Something of the product is not working? File a bug report.'
labels: [bug-report]
body:
  - type: textarea
    id: 'bug'
    attributes:
      label: 'What is the bug?'
      render: shell
    validations:
      required: true
  - type: textarea
    id: 'expected-behavior'
    attributes:
      label: 'How does this bug impact the product?'
      render: shell
    validations:
      required: false
  - type: textarea
    id: 'context'
    attributes:
      label: 'Additional context'
      description: 'Add any other context about the bug report?'
    validations:
      required: false
